// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "Items",
            "endpoint": "https://spb1veacq3.execute-api.us-east-1.amazonaws.com/int",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:450c4e72-09b9-4f59-9775-0aa7b1408685",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qZVl3R5Tf",
    "aws_user_pools_web_client_id": "51rpjj5u3lc953400qf5ci2lgs",
    "oauth": {}
};


export default awsmobile;
